version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> f492947 (.)

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
<<<<<<< HEAD
>>>>>>> fd753da3 (.)
=======
>>>>>>> f492947 (.)
