<?php

declare(strict_types=1);

return [
    'info' => [
        'type_label' => [
            'label' => 'Report Type:',
            'tooltip' => 'Type of generated report',
            'helper_text' => '',
        ],
        'period_label' => [
            'label' => 'Period:',
            'tooltip' => 'Reference period of the report',
            'helper_text' => '',
        ],
        'generated_at_label' => [
            'label' => 'Generated on:',
            'tooltip' => 'Date and time of generation',
            'helper_text' => '',
        ],
        'key' => [
            'label' => 'Key',
            'tooltip' => 'Table key column',
            'helper_text' => '',
        ],
        'value' => [
            'label' => 'Value',
            'tooltip' => 'Table value column',
            'helper_text' => '',
        ],
    ],
    'types' => [
        'paziente_demografico' => 'Patient Demographic Analysis',
        'visite_per_periodo' => 'Visit Statistics by Period',
        'attivita_odontoiatri' => 'Dentist Activity Analysis',
        'isee_analisi' => 'Patient ISEE Analysis',
    ],
    'footer' => [
        'generated_by' => [
            'label' => 'Report generated by: the project',
            'tooltip' => 'Report generation text',
            'helper_text' => '',
        ],
        'copyright' => [
            'label' => '© :year the project. All rights reserved.',
            'tooltip' => 'Copyright',
            'helper_text' => '',
        ],
    ],
]; 