<x-layouts.app>
<div class="bg-[#0019ff]">Ciao</div>
<div class="bg-sky-500">Test</div>
<div class="bg-[#1A467F]">Prova</div>
<div class="bg-[#45465A]">Dark</div>
<div class="h-20">Altezza</div>
<div class="bg-[#0D9488]">Registrati Button</div>
<div class="text-[#E2E8F0]"></div>
<div class="bg-[#E6EBF7]">Section</div>
<div class="text-[#1A467F]">Testo primary</div>
<div class="text-gray-600">Testo subtitle</div>
<div class="text-[#0D9488]"></div>
<div class="hover:text-[#E2E8F0]">Provaaaa</div>
<div class="hover:underline underline-offset-[14]">Ciaoooooo</div>
<div class="lg:h-20 sm:h-12">Logo</div>
<div class="text-center sm:text-center">Testo centrato</div>
<div class="flex justify-around">Flex</div>
<div class="w-80 h-80 rounded-md flex justify-center items-center bg-[#1A467F]">Cards</div>
<div class="border-transparent">Border</div>
<div class="hover:text-[#0D9488]">Hover card</div>
<div class="bg-[#F9F9F9]">Card background</div>
<div class="hover:cursor-pointer">Cursor card</div>
<div class="mx-4">Margin left-right</div>
<div class="bg-[#EBF5FF]">Form background</div>
<div class="bg-[#2E9FBE]">New Primary</div>
<div class="text-[#2E9FBE]">Text new primary</div>
<div class="py-5">Padding 20px</div>
<div class="pb-5">Padding bottom 20px</div>
<div class="text-l">Testo large</div>
<div class="size-7">Size 7</div>
<div class="w-7 h-7">Width height</div>
<div class="flex-col">
    <div class="!bg-[#1A467F]"></div>
</div>
<div class="items-center">
    <div class="!bg-[#1A467F]"></div>
</div>
<div class="text-lg">Testo large</div>
<div class="mb-7">Padding bottom small</div>
<div class="!border-[#0D9488]">Border</div>
<div class="!bg-[#0D9488]">Background</div>
<div class="border-[#1A467F]">Border</div>
<div class="!border-black">BorderBlack</div>
<div class="mb-12">Margin bottom</div>
<div class="m-6">Margin</div>
<div class="w-96">Width</div>
<div class="bg-[#B9C3D1]"></div>
<div class="p-8">Padding</div>
<div class="mb-8">Marginnn</div>
<div class="!py-8">Padding zero</div>
<div class="bg-[#DBE3EE]">Background button azioni</div>
<div class="py-8">Padding Y</div>
<div class="m-12">Margin 12</div>
<div class="mx-0">Margin x</div>
<div class="bg-gradient-to-white from-[#1A467F]">Gradient</div>
<div class="h-96"></div>
<div class="w-[800px]">Width custom</div>
<div class="w-[450px]">Width calendario</div>
<div class="grid-cols-2"></div>
<div class="grid grid-cols-2 gap-4"></div>
<div class="h-auto"></div>
<div class="min-h-screen"></div>
<div class="m-5">Margin five</div>
<div class="px-3">Padding 3</div>
<div class="gap-4">Gap-4</div>
<div class="p-6"></div>
<div class="lg:w-[350px]">Logo width large</div>
<div class="w-[300px]">Width small</div>
<div class="bg-transparent"></div>
<div class="bg-gradient-to-r from-cyan-500 to-blue-500">gradiant</div>
<div class="bg-gradient-to-r from-cyan-500 to-[#1A467F]">gradient</div>
<div class="min-h-screen">screen height</div>
<div class="border-[#1A467F]"></div>
<div class="min-h-[50vh]">min height</div>
<div class="min-h-20 md:min-h-20">min heightt</div>
<div class="min-h-[700px]">min height costum</div>
<div class="w-[350px]">width 350</div>
<div class="w-[700px]">width 700px</div>
</x-layouts.app>    