<x-layouts.app>
<div class="bg-[#0019ff]">Ciao</div>
<div class="bg-sky-500">Test</div>
<div class="bg-[#272C4D]">Prova</div>
<div class="bg-[#45465A]">Dark</div>
<div class="h-20">Altezza</div>
<div class="bg-[#FF5F7E]">Registrati Button</div>
<div class="text-[#E2E8F0]"></div>
<div class="bg-[#E7E7E7]">New background</div>
<div class="bg-[#E6EBF7]">Section</div>
<div class="text-[#272C4D]">Testo primary</div>
<div class="text-gray-600">Testo subtitle</div>
<div class="text-[#FF5F7E]"></div>
<div class="hover:text-[#E2E8F0]">Provaaaa</div>
<div class="hover:underline underline-offset-[14]">Ciaoooooo</div>
<div class="lg:h-20 sm:h-12">Logo</div>
<div class="text-center sm:text-center">Testo centrato</div>
<div class="flex justify-around">Flex</div>
<div class="w-80 h-80 rounded-md flex justify-center items-center bg-[#272C4D]">Cards</div>
<div class="border-transparent">Border</div>
<div class="hover:text-[#FF5F7E]">Hover card</div>
<div class="bg-[#F9F9F9]">Card background</div>
<div class="hover:cursor-pointer">Cursor card</div>
<div class="mx-4">Margin left-right</div>
<div class="bg-[#EBF5FF]">Form background</div>
<div class="bg-[#2E9FBE]">New Primary</div>
<div class="text-[#2E9FBE]">Text new primary</div>
<div class="py-5">Padding 20px</div>
<div class="pb-5">Padding bottom 20px</div>
<div class="text-l">Testo large</div>
<div class="size-7">Size 7</div>
<div class="w-7 h-7">Width height</div>
<div class="flex-col">
    <div class="!bg-[#272C4D]"></div>
</div>
<div class="items-center">
    <div class="!bg-[#1A467F]"></div>
</div>
<div class="text-lg">Testo large</div>
<div class="mb-7">Padding bottom small</div>
<div class="!border-[#FF5F7E]">Border</div>
<div class="!bg-[#FF5F7E]">Background</div>
<div class="border-[#1A467F]">Border</div>
<div class="!border-black">BorderBlack</div>
<div class="mb-12">Margin bottom</div>
<div class="m-6">Margin</div>
<div class="w-96">Width</div>
<div class="bg-[#B9C3D1]"></div>
<div class="p-8">Padding</div>
<div class="mb-8">Marginnn</div>
<div class="!py-8">Padding zero</div>
<div class="bg-[#DBE3EE]">Background button azioni</div>
<div class="py-8">Padding Y</div>
<div class="m-12">Margin 12</div>
<div class="mx-0">Margin x</div>
<div class="bg-gradient-to-white from-[#1A467F]">Gradient</div>
<div class="h-96"></div>
<div class="w-[800px]">Width custom</div>
<div class="w-[450px]">Width calendario</div>
<div class="grid-cols-2"></div>
<div class="grid grid-cols-2 gap-4"></div>
<div class="h-auto"></div>
<div class="min-h-screen"></div>
<div class="m-5">Margin five</div>
<div class="px-3">Padding 3</div>
<div class="gap-4">Gap-4</div>
<div class="p-6"></div>
<div class="lg:w-[350px]">Logo width large</div>
<div class="w-[300px]">Width small</div>
<div class="bg-transparent"></div>
<div class="bg-gradient-to-r from-cyan-500 to-blue-500">gradiant</div>
<div class="bg-gradient-to-r from-cyan-500 to-[#272C4D]">gradient</div>
<div class="min-h-screen">screen height</div>
<div class="border-[#1A467F]"></div>
<div class="min-h-[50vh]">min height</div>
<div class="min-h-20 md:min-h-20">min heightt</div>
<div class="min-h-[700px]">min height costum</div>
<div class="w-[350px]">width 350</div>
<div class="w-[700px]">width 700px</div>
<div class="bg-[#F5F5F5]">background primary chiaro</div>
<div class="ring-[#FF5F7E]">ring primary</div>
<div class="focus:border-[#FF5F7E]">focus primary</div>
<div class="focus:ring-[#FF5F7E]">focus ring primary</div>
<div class="fixed top-0 left-0 right-0 z-50">header fixed</div>
<div class="mt-1.5">margin bottom header</div>
<div class="fixed top-0 left-0 right-0 z-50 h-24">fixed</div>
<div class="!fixed">fix</div>
<div class="w-[750px]">width 1000px</div>
<div class="w-[400px]">width 400px</div>
<div class="min-h-[600px]">min h 600px</div>
<div class="bg-[#B4E1BE]">background success</div>
<div class="text-[#3E783E]">text success</div>
<div class="bg-[#F38B8B]">backgroung error</div>
<div class="text-[#BF0303]">text error</div>
<div class="w-7/12">width 60%</div>
<div class="text-[#272C4D]"></div>
<div class="justify-evenly">justify evenly</div>
<div class="lg:w-7/12">large width calendar</div>
<div class="mt-9">margin top 9</div>
<div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 hidden group-hover:block bg-gray-800 text-white text-sm px-2 py-1 rounded z-10">tooltip</div>
<div class="my-9">margin-top-bottom</div>
</x-layouts.app>