<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Supported Locales
    |--------------------------------------------------------------------------
    |
    | This array contains all the locales supported by the application.
    | Each key should be the locale code and the value should be an array
    | containing information about the locale.
    |
    */
    'supportedLocales' => [
        'it' => [
            'name' => 'Italiano',
            'script' => 'Latn',
            'native' => 'Italiano',
            'regional' => 'it_IT',
        ],
        'en' => [
            'name' => 'English',
            'script' => 'Latn',
            'native' => 'English',
            'regional' => 'en_GB',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Use Current Locale
    |--------------------------------------------------------------------------
    |
    | This value determines whether the current locale will be used for
    | localized URLs. When enabled, the current locale will be included
    | in all URLs generated by the localization package.
    |
    */
    'useCurrentLocale' => true,

    /*
    |--------------------------------------------------------------------------
    | Use Accept Language Header
    |--------------------------------------------------------------------------
    |
    | This value determines whether the Accept-Language header sent by the
    | browser will be used to determine the locale. This can be useful
    | for automatic locale detection.
    |
    */
    'useAcceptLanguageHeader' => true,

    /*
    |--------------------------------------------------------------------------
    | Use Session Locale
    |--------------------------------------------------------------------------
    |
    | This value determines whether the locale stored in the session will
    | be used. This allows users to change the locale and have it persist
    | across requests.
    |
    */
    'useSessionLocale' => true,

    /*
    |--------------------------------------------------------------------------
    | Use Cookie Locale
    |--------------------------------------------------------------------------
    |
    | This value determines whether the locale stored in a cookie will be
    | used. This provides locale persistence across browser sessions.
    |
    */
    'useCookieLocale' => true,

    /*
    |--------------------------------------------------------------------------
    | Hide Default Locale In URL
    |--------------------------------------------------------------------------
    |
    | This value determines whether the default locale will be hidden from
    | URLs. When enabled, URLs for the default locale will not include
    | the locale prefix.
    |
    */
    'hideDefaultLocaleInURL' => false,

    /*
    |--------------------------------------------------------------------------
    | Locales Order
    |--------------------------------------------------------------------------
    |
    | This array defines the order in which locales should be displayed
    | in language selectors and other UI elements.
    |
    */
    'localesOrder' => [
        'it',
        'en',
    ],

    /*
    |--------------------------------------------------------------------------
    | UTF8 Suffix
    |--------------------------------------------------------------------------
    |
    | Character set suffix to be appended to the locale for setting it
    | as the system locale with `setlocale()`.
    |
    */
    'utf8suffix' => env('LARAVELLOCALIZATION_UTF8SUFFIX', '.UTF-8'),
]; 