#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Set cache to array driver before loading anything
putenv('CACHE_DRIVER=array');
$_ENV['CACHE_DRIVER'] = 'array';
$_SERVER['CACHE_DRIVER'] = 'array';

// Bootstrap Laravel
$app = require __DIR__.'/bootstrap/app.php';

// Run the migration
$exitCode = $app->make('Illuminate\Contracts\Console\Kernel')->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

exit($exitCode);
