name: dependabot-auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    
      - name: Dependabot metadata
        id: metadata
<<<<<<< HEAD
<<<<<<< HEAD
        uses: dependabot/fetch-metadata@v1.3.5
=======
        uses: dependabot/fetch-metadata@v1.6.0
>>>>>>> fd753da3 (.)
=======
        uses: dependabot/fetch-metadata@v1.6.0
>>>>>>> f492947 (.)
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Auto-merge Dependabot PRs for semver-minor updates
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Auto-merge Dependabot PRs for semver-patch updates
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
<<<<<<< HEAD
<<<<<<< HEAD
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
=======
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
>>>>>>> fd753da3 (.)
=======
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
>>>>>>> f492947 (.)
